name: yo_chat_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/chatbot.jpg
    - images/google-icon.png
    - assets/key.env
