// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACc0g4Oc1s_nqDay6jXWxdIKOzjhoYG8A',
    appId: '1:316845927247:web:57ee565e76e449887b733a',
    messagingSenderId: '316845927247',
    projectId: 'yo-chat-ai',
    authDomain: 'yo-chat-ai.firebaseapp.com',
    storageBucket: 'yo-chat-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6wPQ-fri6GLfPugPbJmFAYLpmebfN3A',
    appId: '1:316845927247:android:bd635380c608549e7b733a',
    messagingSenderId: '316845927247',
    projectId: 'yo-chat-ai',
    storageBucket: 'yo-chat-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyTfnzGe36JNBFuNTnYLSOJJUazH24oM',
    appId: '1:316845927247:ios:e819476e8cf3b25e7b733a',
    messagingSenderId: '316845927247',
    projectId: 'yo-chat-ai',
    storageBucket: 'yo-chat-ai.firebasestorage.app',
    iosBundleId: 'com.example.yoChatAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyTfnzGe36JNBFuNTnYLSOJJUazH24oM',
    appId: '1:316845927247:ios:e819476e8cf3b25e7b733a',
    messagingSenderId: '316845927247',
    projectId: 'yo-chat-ai',
    storageBucket: 'yo-chat-ai.firebasestorage.app',
    iosBundleId: 'com.example.yoChatAi',
  );
}
